server:
  port: 8080

spring:
  application:
    name: projectstudy-usercenter

  datasource:
    url: jdbc:mysql://47.109.80.234:3306/yupi-pj-usercenter?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "040412"
